services:

  app:
    build: ./app
    container_name: app
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
     MARIADB_HOST: db
     MARIADB_CHARSET: utf8mb4
     MARIADB_COLLATION: utf8mb4_unicode_ci
    networks:
      - 314n
      
  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    networks:
      - 314n

  torgate:
    build: ./torgate
    container_name: torgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n
        
  i2pgate:
    build: ./i2pgate
    container_name: i2pgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n
        
  yggdrasil:
    build: ./yggdrasil
    container_name: yggdrasil
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    
networks:
  314n:

volumes:
  mariadb_data:
