services:
  app:
    build: ./app
    container_name: app
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: db
      MARIADB_CHARSET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    ports:
      - "80:80"
      - "81:81"
    networks:
      - 314n
    depends_on:
      - db

  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - 314n

  torgate:
    build: ./torgate
    container_name: torgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n

  i2pgate:
    build: ./i2pgate
    container_name: i2pgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n

  yggdrasilgate:
    build: ./yggdrasilgate
    container_name: yggdrasilgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 314n
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"

volumes:
  mariadb_data:

networks:
  314n:
