apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-{{ .Values.svc.app.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.app.image.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.svc.app.name }}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app: {{ .Values.svc.app.name }}
          part-of: lb
      spec:
        hostname: {{ .Values.svc.app.name }}
        restartPolicy: {{ .Values.restartPolicy }}
        {{- include "ImagePullSecret" . | nindent 8 }}
        initContainers:
        - name: wait-db
          image: alpine/curl
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            until curl http://{{ .Values.svc.db.name }}:3306 2>&1 | grep -q "1"; do 
              sleep 1
            done
        containers:
        - name: {{ .Values.svc.app.image.name }}
          image: {{ include "ImageRegistry" . }}/{{ .Values.svc.app.image.name }}:{{ .Values.svc.app.image.tag }}
          imagePullPolicy: {{ .Values.svc.app.image.pullPolicy }}
          ports:
          - containerPort: 80
            protocol: TCP
          env:
          - name: MARIADB_HOST
            value: {{ .Values.svc.db.name }}
          - name: MARIADB_CHARSET
            value: utf8mb4
          - name: MARIADB_COLLATION
            value: utf8mb4_unicode_ci
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                key: MARIADB_DATABASE
                name: {{ include "SecretsName" . }}
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                key: MARIADB_USER
                name: {{ include "SecretsName" . }}
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MARIADB_PASSWORD
                name: {{ include "SecretsName" . }}
          - name: ADMIN_LOGIN
            valueFrom:
              secretKeyRef:
                key: ADMIN_LOGIN
                name: {{ include "SecretsName" . }}
          - name: ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                key: ADMIN_PASSWD
                name: {{ include "SecretsName" . }}
          - name: HASHING_SALT
            valueFrom:
              secretKeyRef:
                key: HASHING_SALT
                name: {{ include "SecretsName" . }}
          - name: PUBLIC_HASHING_SALT
            valueFrom:
              secretKeyRef:
                key: PUBLIC_HASHING_SALT
                name: {{ include "SecretsName" . }}
          - name: USE_HWT
            valueFrom:
              secretKeyRef:
                key: USE_HWT
                name: {{ include "SecretsName" . }}
          - name: ALLOW_LEGACY_HASHES
            valueFrom:
              secretKeyRef:
                key: ALLOW_LEGACY_HASHES
                name: {{ include "SecretsName" . }}
          - name: ALLOW_GUESTS
            valueFrom:
              secretKeyRef:
                key: ALLOW_GUESTS
                name: {{ include "SecretsName" . }}
          - name: IDENTIFY_GUESTS_BY_IP
            valueFrom:
              secretKeyRef:
                key: IDENTIFY_GUESTS_BY_IP
                name: {{ include "SecretsName" . }}
          - name: ALLOW_ANONYMOUS_POSTING
            valueFrom:
              secretKeyRef:
                key: ALLOW_ANONYMOUS_POSTING
                name: {{ include "SecretsName" . }}
          - name: ALLOW_USER_BOARDS
            valueFrom:
              secretKeyRef:
                key: ALLOW_USER_BOARDS
                name: {{ include "SecretsName" . }}
          - name: STORE_USER_IP
            valueFrom:
              secretKeyRef:
                key: STORE_USER_IP
                name: {{ include "SecretsName" . }}
          - name: LOCAL_IP_LIST
            valueFrom:
              secretKeyRef:
                key: LOCAL_IP_LIST
                name: {{ include "SecretsName" . }}
          - name: GUEST_ACCOUNT_TTL
            valueFrom:
              secretKeyRef:
                key: GUEST_ACCOUNT_TTL
                name: {{ include "SecretsName" . }}
          - name: BOARDS_PER_USER
            valueFrom:
              secretKeyRef:
                key: BOARDS_PER_USER
                name: {{ include "SecretsName" . }}

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.svc.app.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    selector:
      app: {{ .Values.svc.app.name }}
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    clusterIP: None

kind: List
metadata:
  name: "app-list"
