---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.db.replicas }}
  serviceName: "db"
  minReadySeconds: 10
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
        {{- with .Values.db.podLabels }}
        {{ toYaml . }}
        {{- end }}
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{ toYaml . }}
      {{- end }}
    spec:
      hostname: db
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: mariadb
        image: mariadb:{{ .Values.db.image.tag }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        ports:
        - containerPort: 3306
          protocol: TCP
        {{- $secretName := .Values.secret | default "314n-secret" }}
        {{- with .Values.db.env }}
        env:
          {{- range . }}
          - name: {{ .name }}
            {{- if .value }}
            value: {{ .value | quote }}
            {{- else if .valueFrom }}
            valueFrom:
              {{- $valueFrom := .valueFrom }}
              {{- if kindIs "string" $valueFrom.secretKeyRef.name }}
              secretKeyRef:
                key: {{ $valueFrom.secretKeyRef.key }}
                name: {{ $secretName | quote }}
              {{- else }}
                {{- toYaml $valueFrom }}
              {{- end }}
            {{- end }}
            {{- end }}
        {{- end }}
        volumeMounts:
        - name: {{ .Release.Name }}-db-pvc
          mountPath: /var/lib/mysql
          subPath: mariadb_data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{ .Release.Name }}-db-pvc
    spec:
      accessModes: [ {{ .Values.db.persistentVolume.storageClass.accessMode }} ]
      resources:
        requests:
          storage: "{{ .Values.db.persistentVolume.size }}"
      storageClassName: {{ .Values.db.persistentVolume.storageClass.name | default "" }}
      volumeMode: Filesystem
---            
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None