apiVersion: v1
kind: Service
metadata:
  name: db-314n-expose
  namespace: 314n
spec:
  ports:
  - name: db
    port: 3306
    targetPort: 3306
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
