apiVersion: v1
kind: Service
metadata:
  name: db-314n-expose
  namespace: 314n-dev
spec:
  ports:
  - name: db
    port: 33060
    targetPort: 33060
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
