apiVersion: v1
kind: Service
metadata:
  name: frontend-314n-expose
  namespace: 314n
spec:
  ports:
  - name: app
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
