name: Docker build

on:
  pull_request:
    branches:
      - main

env:
  APP_IMAGE_NAME: 314n
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasilgate

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter
        uses: tj-actions/changed-files@v46.0.5
        id: filter
        with:
          files_yaml: |
            app:
              - 'app/**'
            torgate:
              - 'torgate/**'
            i2pgate:
              - 'i2pgate/**'
            yggdrasilgate:
              - 'yggdrasilgate/**'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build 314n
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.app_any_changed == 'true'
        with:
          context: app/.
          file: app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.APP_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build torgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.torgate_any_changed == 'true'
        with:
          context: torgate/.
          file: torgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build i2pgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.i2pgate_any_changed == 'true'
        with:
          context: i2pgate/.
          file: i2pgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build yggdrasilgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.yggdrasilgate_any_changed == 'true'
        with:
          context: yggdrasilgate/.
          file: yggdrasilgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
