name: Docker build

on: pull_request

env:
  APP_IMAGE_NAME: 314n
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasil

jobs:

  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      buildDocker: ${{ steps.diff.outputs.buildDocker }}
    steps:
    - uses: dorny/paths-filter@v3
      id: diff
      with:
        filters: |
          buildDocker:
            - 'app/**'
            - 'i2pgate/**'
            - 'torgate/**'
            - 'yggdrasil/**'

  buildDocker:
    runs-on: ubuntu-latest
    needs: diff
    if: ${{ needs.diff.outputs.buildDocker == 'true' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            torgate:
              - 'torgate/**'
            i2pgate:
              - 'i2pgate/**'
            yggdrasilgate:
              - 'yggdrasil/**'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      -
        name: Build 314n
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.app == 'true'
        with:
          context: app/.
          file: app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.APP_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build torgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.torgate == 'true'
        with:
          context: torgate/.
          file: torgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build i2pgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.i2pgate == 'true'
        with:
          context: i2pgate/.
          file: i2pgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build yggdrasilgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.yggdrasilgate == 'true'
        with:
          context: yggdrasil/.
          file: yggdrasil/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
