name: Helm build

on:
  pull_request:
    branches:
      - main

jobs:
  buildHelm:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter
        uses: tj-actions/changed-files@v46.0.5
        id: filter
        with:
          files_yaml: |
            buildHelm:
              - 'k8s/helm/**'
              - '.cr.yaml'
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        if: steps.filter.outputs.buildHelm_any_changed == 'true'
        with:
          charts_dir: k8s/helm/charts
          config: k8s/.cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
      - name: Login to ghcr
        uses: docker/login-action@v3.0.0
        if: steps.filter.outputs.buildHelm_any_changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push charts to ghcr
        if: steps.filter.outputs.buildHelm_any_changed == 'true'
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/helm"
          done
